server:
  port: 8090
  
  
spring:
  application:
    name: sc-zuul-server


eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${random.value}
    prefer-ip-address: true


zuul:
  routes:
    sc-products-service:
      service-id: sc-products-service
      path: /api/products/**
    sc-items-service:
      service-id: sc-items-service
      path: /api/items/**
    
ribbon.ConnectTimeout: 30000
ribbon.ReadTimeout: 30000