server:
  port: 8761
  
  
spring:
  application:
    name: sc-discovery-server  cloud:    loadbalancer:      ribbon:        enabled: false
    
    
eureka:  client:    register-with-eureka: false
    fetch-registry: false
    
logging:  level:    root: warn
    