server:
  port: ${PORT:0}


spring:
  application:
    name: sc-items-service

    
eureka:
  instance:
    instance-id: ${spring.application.name}:${random.value}
    prefer-ip-address: true
  client:
    service-url:
      default-zone: http://localhost:8761/eureka

      
logging:
  level:
    root: warn